#!/usr/bin/env node
// Vendors the brand fonts as a generated JS module (src/fonts.css.js) with
// base64 @font-face rules. Embedded data means local Chrome, Browser
// Rendering, and the final PDF all use the exact same metrics — and Lulu
// requires embedded fonts. Re-run only when changing the font set.

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const FAMILIES =
  "family=Fjalla+One&family=Lora:ital,wght@0,400;0,700;1,400;1,700&family=Courier+Prime:ital,wght@0,400;0,700;1,400";

// A woff2-capable UA makes Google Fonts return woff2 sources.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

const css = await (
  await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}&display=block`, {
    headers: { "User-Agent": UA },
  })
).text();

// Parse @font-face blocks; keep only the latin subset of each face.
const faces = [];
const blockRe = /\/\* (\w[\w-]*) \*\/\s*@font-face\s*\{([^}]+)\}/g;
for (const [, subset, body] of css.matchAll(blockRe)) {
  if (subset !== "latin") continue;
  const get = (prop) => body.match(new RegExp(`${prop}:\\s*([^;]+);`))?.[1].trim();
  faces.push({
    family: get("font-family").replace(/'/g, ""),
    style: get("font-style"),
    weight: get("font-weight"),
    url: body.match(/url\((https:[^)]+\.woff2)\)/)?.[1],
  });
}

let out = "// GENERATED by scripts/build-fonts.mjs — do not edit by hand.\n";
out += "export const FONTS_CSS = `\n";
for (const face of faces) {
  process.stdout.write(`${face.family} ${face.weight} ${face.style} ... `);
  const buf = Buffer.from(await (await fetch(face.url)).arrayBuffer());
  console.log(`${Math.round(buf.length / 1024)}KB`);
  out += `@font-face { font-family: '${face.family}'; font-style: ${face.style}; font-weight: ${face.weight}; src: url(data:font/woff2;base64,${buf.toString("base64")}) format('woff2'); }\n`;
}
out += "`;\n";

const dest = resolve(dirname(fileURLToPath(import.meta.url)), "../src/fonts.css.js");
writeFileSync(dest, out);
console.log(`${faces.length} faces -> ${dest} (${Math.round(out.length / 1024)}KB)`);
